export const creative: { src: string; caption: string }[] = [
  { src: '/media/creative-01.jpg', caption: 'Creative work 01' },
  { src: '/media/creative-02.webp', caption: 'Creative work 02' },
  { src: '/media/creative-03.webp', caption: 'Creative work 03' },
  { src: '/media/creative-04.webp', caption: 'Creative work 04' },
  { src: '/media/creative-05.webp', caption: 'Creative work 05' },
  { src: '/media/creative-06.webp', caption: 'Creative work 06' },
  { src: '/media/creative-07.png', caption: 'Creative work 07' },
  { src: '/media/creative-08.webp', caption: 'Creative work 08' },
  { src: '/media/creative-09.webp', caption: 'Creative work 09' },
  { src: '/media/creative-10.webp', caption: 'Creative work 10' },
  { src: '/media/creative-11.webp', caption: 'Creative work 11' },
  { src: '/media/creative-12.webp', caption: 'Creative work 12' },
  { src: '/media/creative-13.webp', caption: 'Creative work 13' },
];
