import { readdirSync, writeFileSync, statSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

const DECKS_DIR = resolve(process.cwd(), 'src/decks');
const VARIANTS = ['claude', 'design', 'stitch', 'hermes'] as const;

function isDir(p: string): boolean {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}

function listDecks(): string[] {
  if (!existsSync(DECKS_DIR)) return [];
  return readdirSync(DECKS_DIR).filter((name) => isDir(join(DECKS_DIR, name)));
}

function listSlides(deckId: string): string[] {
  const slidesDir = join(DECKS_DIR, deckId, 'slides');
  if (!existsSync(slidesDir)) return [];
  return readdirSync(slidesDir)
    .filter((name) => isDir(join(slidesDir, name)))
    .sort();
}

function generateForDeck(deckId: string): string {
  const slides = listSlides(deckId);
  const imports: string[] = [];
  const slideEntries: string[] = [];

  for (const slideId of slides) {
    const variantEntries: string[] = [];
    for (const v of VARIANTS) {
      const file = join(DECKS_DIR, deckId, 'slides', slideId, `${v}.tsx`);
      if (!existsSync(file)) continue;
      const alias = `s_${slideId.replace(/-/g, '_')}_${v}`;
      imports.push(`import * as ${alias} from './slides/${slideId}/${v}';`);
      variantEntries.push(`    ${v}: ${alias} as unknown as SlideModule,`);
    }
    slideEntries.push(`  {
    id: '${slideId}',
    variants: {
${variantEntries.join('\n')}
    },
  },`);
  }

  return `// AUTO-GENERATED by scripts/gen-registry.ts — do not edit.
import type { SlideEntry, SlideModule } from '@/lib/types';
${imports.join('\n')}

export const slides: SlideEntry[] = [
${slideEntries.join('\n')}
];
`;
}

function main(): void {
  const decks = listDecks();
  if (decks.length === 0) {
    console.log('[gen-registry] no decks found in src/decks/');
    return;
  }
  for (const deckId of decks) {
    const out = generateForDeck(deckId);
    const target = join(DECKS_DIR, deckId, '_generated.ts');
    writeFileSync(target, out, 'utf8');
    console.log(`[gen-registry] wrote ${target}`);
  }
}

main();
